import { Header } from "@/components/common/Header";
import { systemUi } from "@/fonts/config";
import { cn } from "@/utils/cn";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("bg-dark text-white", systemUi.className)}>
        <Header />
        {children}
      </body>
    </html>
  );
}
